---
- block:
  - include_tasks: jc_init_config.yml
  tags:
    - jc-init

- block:
  - include_tasks: jc_plugins.yml
  tags:
    - jc-plugins

- block:
  - include_tasks: jc_search_config.yml
  - include_tasks: jc_config.yml
  tags:
    - jc-config
