---
- name: Restart Jenkins
  systemd:
    state: restarted
    daemon_reload: yes
    name: jenkins
  notify: Wait for Jenkins to start up

- name: Wait for Jenkins to start up
  uri:
    url: "{{ jc_url }}/login"
    status_code: 200
    timeout: 5
  register: jc_service_status
  # Keep trying for 5 mins in 5 sec intervals
  retries: 60
  delay: 5
  until: >
      'status' in jc_service_status and
      jc_service_status['status'] == 200

- name: Reload Jenkins Configuration as Code
  jenkins_script:
    script: |
      import io.jenkins.plugins.casc.ConfigurationAsCode;
      ConfigurationAsCode.get().configure()
    user: "{{ jc_admin_username }}"
    password: "{{ jc_admin_password }}"
    url: "{{ jc_url }}"
  changed_when: true
